/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param id 
    * @param packageNumber 
    * @param userId 
    * @param receivedAt 
    * @param dimensions 
    * @param dimensionsUnit 
    * @param weight 
    * @param weightUnit 
    * @param packageType 
    * @param from 
    * @param days 
    * @param additionalFees 
    * @param isSplit 
    * @param splitCount 
*/

@Parcelize
data class PackageList (

    @SerializedName("id")
    var id: Int? = null,
    @SerializedName("package_number")
    var packageNumber: String? = null,
    @SerializedName("user_id")
    var userId: Int? = null,
    @SerializedName("received_at")
    var receivedAt: String? = null,
    @SerializedName("dimensions")
    var dimensions: String? = null,
    @SerializedName("dimensions_unit")
    var dimensionsUnit: String? = null,
    @SerializedName("weight")
    var weight: BigDecimal? = null,
    @SerializedName("weight_unit")
    var weightUnit: String? = null,
    @SerializedName("package_type")
    var packageType: String? = null,
    @SerializedName("from")
    var from: String? = null,
    @SerializedName("days")
    var days: String? = null,
    @SerializedName("additional_fees")
    var additionalFees: BigDecimal? = null,
    @SerializedName("is_split")
    var isSplit: Boolean? = null,
    @SerializedName("split_count")
    var splitCount: Int? = null
)
:Parcelable




