/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param currentPage 
    * @param nextPage 
    * @param prevPage 
    * @param totalPages 
    * @param totalCount 
*/

@Parcelize
data class Pagination (

    @SerializedName("current_page")
    var currentPage: Int? = null,
    @SerializedName("next_page")
    var nextPage: Int? = null,
    @SerializedName("prev_page")
    var prevPage: Int? = null,
    @SerializedName("total_pages")
    var totalPages: Int? = null,
    @SerializedName("total_count")
    var totalCount: Int? = null
)
:Parcelable




