/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param carrierFees 
    * @param consolidatedFees 
    * @param additionalFees 
    * @param totalCharges 
*/

@Parcelize
data class InvoiceDetails (

    @SerializedName("carrier_fees")
    var carrierFees: BigDecimal? = null,
    @SerializedName("consolidated_fees")
    var consolidatedFees: BigDecimal? = null,
    @SerializedName("additional_fees")
    var additionalFees: BigDecimal? = null,
    @SerializedName("total_charges")
    var totalCharges: BigDecimal? = null
)
:Parcelable




