/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param id 
    * @param label 
    * @param phone 
    * @param state 
    * @param city 
    * @param street1 
    * @param street2 
    * @param postalCode 
    * @param receiverName 
    * @param isBillingAddress 
    * @param countryCodeId 
    * @param country 
    * @param phoneCode 
*/

@Parcelize
data class AddressDetails (

    @SerializedName("id")
    var id: Int? = null,
    @SerializedName("label")
    var label: String? = null,
    @SerializedName("phone")
    var phone: String? = null,
    @SerializedName("state")
    var state: String? = null,
    @SerializedName("city")
    var city: String? = null,
    @SerializedName("street_1")
    var street1: String? = null,
    @SerializedName("street_2")
    var street2: String? = null,
    @SerializedName("postal_code")
    var postalCode: String? = null,
    @SerializedName("receiver_name")
    var receiverName: String? = null,
    @SerializedName("is_billing_address")
    var isBillingAddress: Boolean? = null,
    @SerializedName("country_code_id")
    var countryCodeId: String? = null,
    @SerializedName("country")
    var country: String? = null,
    @SerializedName("phone_code")
    var phoneCode: String? = null
)
:Parcelable




