/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param id 
    * @param stripePaymentId 
    * @param payableAmount 
    * @param currency 
    * @param status 
    * @param orderId 
    * @param balanceTransaction 
    * @param paymentIntentId 
    * @param paymentIntentClientSecret 
    * @param requiresAction 
    * @param createdAt 
*/

@Parcelize
data class OrderPaymentDetails (

    @SerializedName("id")
    var id: Int? = null,
    @SerializedName("stripe_payment_id")
    var stripePaymentId: String? = null,
    @SerializedName("payable_amount")
    var payableAmount: BigDecimal? = null,
    @SerializedName("currency")
    var currency: String? = null,
    @SerializedName("status")
    var status: String? = null,
    @SerializedName("order_id")
    var orderId: Int? = null,
    @SerializedName("balance_transaction")
    var balanceTransaction: String? = null,
    @SerializedName("payment_intent_id")
    var paymentIntentId: String? = null,
    @SerializedName("payment_intent_client_secret")
    var paymentIntentClientSecret: String? = null,
    @SerializedName("requires_action")
    var requiresAction: Boolean? = null,
    @SerializedName("created_at")
    var createdAt: String? = null
)
:Parcelable




