/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param conciergeId 
    * @param payableAmount 
    * @param isPayment 
    * @param status 
    * @param userId 
    * @param createdAt 
    * @param paymentId 
    * @param paymentIntentId 
    * @param paymentIntentClientSecret 
    * @param requiresAction 
    * @param paymentStatus 
*/

@Parcelize
data class CreatePaymentResponseData (

    @SerializedName("concierge_id")
    var conciergeId: Int? = null,
    @SerializedName("payable_amount")
    var payableAmount: BigDecimal? = null,
    @SerializedName("is_payment")
    var isPayment: Boolean? = null,
    @SerializedName("status")
    var status: String? = null,
    @SerializedName("user_id")
    var userId: Int? = null,
    @SerializedName("created_at")
    var createdAt: String? = null,
    @SerializedName("payment_id")
    var paymentId: String? = null,
    @SerializedName("payment_intent_id")
    var paymentIntentId: String? = null,
    @SerializedName("payment_intent_client_secret")
    var paymentIntentClientSecret: String? = null,
    @SerializedName("requires_action")
    var requiresAction: Boolean? = null,
    @SerializedName("payment_status")
    var paymentStatus: String? = null
)
:Parcelable




