/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param id 
    * @param orderKey 
    * @param orderNumber 
    * @param orderStatus 
    * @param carrierUsed 
    * @param serviceName 
    * @param serviceCode 
    * @param shippingCost 
    * @param processedOn 
*/

@Parcelize
data class CreateOrderDetails (

    @SerializedName("id")
    var id: Int? = null,
    @SerializedName("order_key")
    var orderKey: String? = null,
    @SerializedName("order_number")
    var orderNumber: String? = null,
    @SerializedName("order_status")
    var orderStatus: String? = null,
    @SerializedName("carrier_used")
    var carrierUsed: String? = null,
    @SerializedName("service_name")
    var serviceName: String? = null,
    @SerializedName("service_code")
    var serviceCode: String? = null,
    @SerializedName("shipping_cost")
    var shippingCost: BigDecimal? = null,
    @SerializedName("processed_on")
    var processedOn: String? = null
)
:Parcelable




