/*
 * USend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sumand.spaceo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.base.network.model

import com.google.gson.annotations.SerializedName

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
/**
* 
    * @param id 
    * @param isRead 
    * @param notificationType 
    * @param createdAt 
    * @param notifiableType 
    * @param notifiableId 
    * @param title 
    * @param message 
*/

@Parcelize
data class UserNotification (

    @SerializedName("id")
    var id: Int? = null,
    @SerializedName("is_read")
    var isRead: Boolean? = null,
    @SerializedName("notification_type")
    var notificationType: String? = null,
    @SerializedName("created_at")
    var createdAt: String? = null,
    @SerializedName("notifiable_type")
    var notifiableType: String? = null,
    @SerializedName("notifiable_id")
    var notifiableId: Int? = null,
    @SerializedName("title")
    var title: String? = null,
    @SerializedName("message")
    var message: String? = null
)
:Parcelable




